import { addYears } from 'date-fns';

import { DEFAULT_INFLATION_CONFIG, DEFAULT_TAX_CONFIG } from './defaults';
import type { SavingsPlan } from './types';
import { createId } from '../utils/id';

const today = new Date();
const todayIso = today.toISOString().slice(0, 10);
const in20Years = addYears(today, 20).toISOString().slice(0, 10);

export const createDemoPlans = (): SavingsPlan[] => {
  return [
    {
      id: createId(),
      name: 'DEMO: ETF-Sparplan',
      description: 'Beispieldaten fuer ETF-Sparplan mit monatlicher Sparrate.',
      productType: 'etf',
      category: 'Vermoegensaufbau',
      color: '#1f7a8c',
      currency: 'EUR',
      startDate: todayIso,
      endDate: in20Years,
      initialValueCents: 1_000_000,
      isActive: true,
      isArchived: false,
      visibleInChart: true,
      returnMode: 'forecast',
      forecastReturns: { minAnnualPercent: 3, baseAnnualPercent: 6, maxAnnualPercent: 9 },
      contributionRules: [
        {
          id: createId(),
          amountCents: 50_000,
          startDate: todayIso,
          frequency: 'monthly',
          execution: 'period-start',
        },
      ],
      subsidyRules: [],
      pauseRules: [],
      feeRules: [],
      taxConfig: { ...DEFAULT_TAX_CONFIG },
      inflationConfig: { ...DEFAULT_INFLATION_CONFIG },
      withdrawalRules: [],
    },
    {
      id: createId(),
      name: 'DEMO: Rentenversicherung',
      description: 'Monatliche Einzahlung mit fester Laufzeit und Gebuehren.',
      productType: 'pension-insurance',
      category: 'Altersvorsorge',
      color: '#6b8e23',
      currency: 'EUR',
      startDate: todayIso,
      endDate: in20Years,
      initialValueCents: 0,
      isActive: true,
      isArchived: false,
      visibleInChart: true,
      returnMode: 'forecast',
      forecastReturns: { fixedAnnualPercent: 3.5 },
      contributionRules: [
        {
          id: createId(),
          amountCents: 25_000,
          startDate: todayIso,
          frequency: 'monthly',
          execution: 'period-end',
        },
      ],
      subsidyRules: [],
      pauseRules: [],
      feeRules: [
        {
          id: createId(),
          name: 'Verwaltungsgebuehr',
          type: 'fixed-monthly',
          amountCents: 400,
          startDate: todayIso,
          paymentFrequency: 'monthly',
          taxRelevant: true,
        },
      ],
      taxConfig: { ...DEFAULT_TAX_CONFIG },
      inflationConfig: { ...DEFAULT_INFLATION_CONFIG },
      withdrawalRules: [],
    },
    {
      id: createId(),
      name: 'DEMO: bAV',
      description: 'Eigenanteil plus Arbeitgeberzuschuss.',
      productType: 'company-pension',
      category: 'Altersvorsorge',
      color: '#8a5a44',
      currency: 'EUR',
      startDate: todayIso,
      endDate: in20Years,
      initialValueCents: 0,
      isActive: true,
      isArchived: false,
      visibleInChart: true,
      returnMode: 'forecast',
      forecastReturns: { fixedAnnualPercent: 4.5 },
      contributionRules: [
        {
          id: createId(),
          amountCents: 20_000,
          startDate: todayIso,
          frequency: 'monthly',
          execution: 'period-start',
        },
      ],
      subsidyRules: [
        {
          id: createId(),
          type: 'employer',
          label: 'Arbeitgeberzuschuss',
          amountCents: 7_000,
          startDate: todayIso,
          frequency: 'monthly',
          continueDuringPause: true,
        },
      ],
      pauseRules: [],
      feeRules: [],
      taxConfig: { ...DEFAULT_TAX_CONFIG },
      inflationConfig: { ...DEFAULT_INFLATION_CONFIG },
      withdrawalRules: [],
    },
    {
      id: createId(),
      name: 'DEMO: Tagesgeld',
      description: 'Tagesgeldkonto mit variabler Verzinsung.',
      productType: 'savings-account',
      category: 'Liquiditaet',
      color: '#2e4057',
      currency: 'EUR',
      startDate: todayIso,
      endDate: in20Years,
      initialValueCents: 500_000,
      isActive: true,
      isArchived: false,
      visibleInChart: true,
      returnMode: 'forecast',
      forecastReturns: { minAnnualPercent: 1, baseAnnualPercent: 2, maxAnnualPercent: 3 },
      contributionRules: [],
      subsidyRules: [],
      pauseRules: [],
      feeRules: [],
      taxConfig: { ...DEFAULT_TAX_CONFIG },
      inflationConfig: { ...DEFAULT_INFLATION_CONFIG },
      withdrawalRules: [],
    },
    {
      id: createId(),
      name: 'DEMO: Sparpause-Szenario',
      description: 'Sparplan mit einer einjaehrigen Sparpause.',
      productType: 'generic-savings-plan',
      category: 'Szenario',
      color: '#b56576',
      currency: 'EUR',
      startDate: todayIso,
      endDate: in20Years,
      initialValueCents: 0,
      isActive: true,
      isArchived: false,
      visibleInChart: true,
      returnMode: 'forecast',
      forecastReturns: { baseAnnualPercent: 5, minAnnualPercent: 3, maxAnnualPercent: 7 },
      contributionRules: [
        {
          id: createId(),
          amountCents: 30_000,
          startDate: todayIso,
          frequency: 'monthly',
          execution: 'period-start',
        },
      ],
      subsidyRules: [],
      pauseRules: [
        {
          id: createId(),
          label: 'Sparpause',
          startDate: new Date(today.getFullYear() + 2, today.getMonth(), 1)
            .toISOString()
            .slice(0, 10),
          endDate: new Date(today.getFullYear() + 3, today.getMonth(), 0)
            .toISOString()
            .slice(0, 10),
          pauseOwnContributions: true,
          pauseSubsidies: false,
          pauseFees: true,
          continueInterestAccrual: true,
        },
      ],
      feeRules: [],
      taxConfig: { ...DEFAULT_TAX_CONFIG },
      inflationConfig: { ...DEFAULT_INFLATION_CONFIG },
      withdrawalRules: [],
    },
  ];
};
