import { useEffect, useState, type ReactNode } from 'react';

import type {
  ContributionFrequency,
  FeeRule,
  FeeType,
  PauseRule,
  SavingsPlan,
  SubsidyRule,
  WithdrawalRule,
} from '../domain/types';
import { createId } from '../utils/id';
import { toCents } from '../utils/money';

interface PlanEditorProps {
  plan?: SavingsPlan;
  onSave: (plan: SavingsPlan) => Promise<void>;
}

const tabs = ['Allgemein', 'Einzahlungen', 'Zuschuesse', 'Rendite und Marktdaten', 'Sparpausen', 'Gebuehren', 'Steuern', 'Inflation', 'Auszahlungen', 'Vorschau'] as const;
const frequencies: { value: ContributionFrequency; label: string }[] = [
  { value: 'one-time', label: 'Einmalig' }, { value: 'weekly', label: 'Woechentlich' }, { value: 'biweekly', label: 'Zweiwoechentlich' }, { value: 'monthly', label: 'Monatlich' }, { value: 'quarterly', label: 'Quartalsweise' }, { value: 'semi-annual', label: 'Halbjaehrlich' }, { value: 'annual', label: 'Jaehrlich' },
];
const feeTypes: { value: FeeType; label: string; isPercent?: boolean }[] = [
  { value: 'one-time-closing', label: 'Abschlussgebuehr' }, { value: 'one-time-setup', label: 'Einrichtungsgebuehr' }, { value: 'fixed-monthly', label: 'Fix monatlich' }, { value: 'fixed-annual', label: 'Fix jaehrlich' }, { value: 'percentage-annual-management', label: 'Verwaltung p.a.', isPercent: true }, { value: 'percentage-assets-under-management', label: 'Auf Vermoegen', isPercent: true }, { value: 'purchase-fixed', label: 'Kaufgebuehr' }, { value: 'purchase-percentage', label: 'Kaufgebuehr in %', isPercent: true }, { value: 'sell-fee', label: 'Verkaufsgebuehr' }, { value: 'other', label: 'Sonstige Gebuehr' },
];

const centsToEuro = (cents?: number) => (cents ?? 0) / 100;
const emptyToUndefined = (value: string): number | undefined => value === '' ? undefined : Number(value);
const frequencySelect = () => frequencies.map((item) => <option key={item.value} value={item.value}>{item.label}</option>);

interface RuleSectionProps { title: string; onAdd: () => void; children: ReactNode; }
const RuleSection = ({ title, onAdd, children }: RuleSectionProps) => <section className="rule-section"><div className="rule-section-header"><h4>{title}</h4><button type="button" onClick={onAdd}>Regel hinzufuegen</button></div>{children}</section>;

export const PlanEditor = ({ plan, onSave }: PlanEditorProps) => {
  const [activeTab, setActiveTab] = useState<(typeof tabs)[number]>('Allgemein');
  const [draft, setDraft] = useState<SavingsPlan | undefined>(plan);
  const [error, setError] = useState<string>();
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => { setDraft(plan); setError(undefined); }, [plan]);
  if (!draft) return <section className="editor-card">Bitte Sparplan auswaehlen.</section>;

  const update = (changes: Partial<SavingsPlan>) => setDraft({ ...draft, ...changes });
  const validate = (next: SavingsPlan) => {
    if (!next.name.trim()) return 'Leere Namen sind nicht zulaessig.';
    if (next.endDate && next.endDate < next.startDate) return 'Enddatum darf nicht vor dem Startdatum liegen.';
    if (next.initialValueCents < 0) return 'Anfangswert darf nicht negativ sein.';
    if (next.pauseRules.some((item) => !item.label.trim() || item.endDate < item.startDate)) return 'Jede Sparpause braucht Bezeichnung sowie ein gueltiges Start- und Enddatum.';
    if (next.contributionRules.some((item) => item.amountCents < 0 || (item.endDate !== undefined && item.endDate < item.startDate))) return 'Einzahlungsregeln brauchen nicht-negative Betraege und gueltige Zeitraeume.';
    if (next.subsidyRules.some((item) => item.amountCents < 0 || (item.endDate !== undefined && item.endDate < item.startDate))) return 'Zuschussregeln brauchen nicht-negative Betraege und gueltige Zeitraeume.';
    return undefined;
  };
  const save = async () => {
    const validation = validate(draft);
    if (validation) { setError(validation); return; }
    setError(undefined); setIsSaving(true);
    try { await onSave(draft); } catch (saveError) { setError(`Speichern fehlgeschlagen: ${(saveError as Error).message}`); } finally { setIsSaving(false); }
  };
  const replaceContribution = (id: string, changes: Partial<SavingsPlan['contributionRules'][number]>) => update({ contributionRules: draft.contributionRules.map((item) => item.id === id ? { ...item, ...changes } : item) });
  const replaceSubsidy = (id: string, changes: Partial<SubsidyRule>) => update({ subsidyRules: draft.subsidyRules.map((item) => item.id === id ? { ...item, ...changes } : item) });
  const replacePause = (id: string, changes: Partial<PauseRule>) => update({ pauseRules: draft.pauseRules.map((item) => item.id === id ? { ...item, ...changes } : item) });
  const replaceFee = (id: string, changes: Partial<FeeRule>) => update({ feeRules: draft.feeRules.map((item) => item.id === id ? { ...item, ...changes } : item) });
  const replaceWithdrawal = (id: string, changes: Partial<WithdrawalRule>) => update({ withdrawalRules: draft.withdrawalRules.map((item) => item.id === id ? { ...item, ...changes } : item) });

  return <section className="editor-card" aria-label="Sparplan Editor">
    <header className="editor-head"><h3>Editor</h3><div className="tabs" role="tablist" aria-label="Editor Tabs">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={activeTab === tab} className={activeTab === tab ? 'active' : ''} type="button" onClick={() => setActiveTab(tab)}>{tab}</button>)}</div></header>

    {activeTab === 'Allgemein' && <div className="editor-grid">
      <label>Name<input value={draft.name} onChange={(event) => update({ name: event.target.value })} /></label>
      <label>Beschreibung<input value={draft.description ?? ''} onChange={(event) => update({ description: event.target.value })} /></label>
      <label>Produkttyp<select value={draft.productType} onChange={(event) => update({ productType: event.target.value as SavingsPlan['productType'] })}><option value="etf">ETF</option><option value="stock-portfolio">Aktiendepot</option><option value="savings-account">Tagesgeld</option><option value="fixed-deposit">Festgeld</option><option value="pension-insurance">Rentenversicherung</option><option value="riester">Riester</option><option value="company-pension">bAV</option><option value="fund">Fonds</option><option value="crypto">Krypto</option><option value="generic-savings-plan">Allgemeiner Sparplan</option><option value="manual-product">Manuelles Produkt</option></select></label>
      <label>Kategorie<input value={draft.category} onChange={(event) => update({ category: event.target.value })} /></label>
      <label>Waehrung<input value={draft.currency} onChange={(event) => update({ currency: event.target.value.toUpperCase() })} /></label>
      <label>Startdatum<input type="date" value={draft.startDate} onChange={(event) => update({ startDate: event.target.value })} /></label>
      <label>Enddatum<input type="date" value={draft.endDate ?? ''} onChange={(event) => update({ endDate: event.target.value || undefined })} /></label>
      <label>Anfangswert in EUR<input type="number" min="0" step="0.01" value={centsToEuro(draft.initialValueCents)} onChange={(event) => update({ initialValueCents: toCents(Number(event.target.value || 0)) })} /></label>
      <label>Manueller Wert in EUR<input type="number" min="0" step="0.01" value={centsToEuro(draft.currentManualValueCents)} onChange={(event) => update({ currentManualValueCents: toCents(Number(event.target.value || 0)) })} /></label>
      <label>Farbe<input type="color" value={draft.color} onChange={(event) => update({ color: event.target.value })} /></label>
      <label className="toggle-field"><input type="checkbox" checked={draft.isActive} onChange={(event) => update({ isActive: event.target.checked })} /> Aktiv</label>
      <label className="toggle-field"><input type="checkbox" checked={draft.isArchived} onChange={(event) => update({ isArchived: event.target.checked })} /> Archiviert</label>
    </div>}

    {activeTab === 'Einzahlungen' && <RuleSection title="Einzahlungsregeln" onAdd={() => update({ contributionRules: [...draft.contributionRules, { id: createId(), amountCents: 0, startDate: draft.startDate, frequency: 'monthly', execution: 'period-start' }] })}>{draft.contributionRules.map((rule) => <div className="rule-card" key={rule.id}><div className="editor-grid">
      <label>Betrag in EUR<input type="number" min="0" step="0.01" value={centsToEuro(rule.amountCents)} onChange={(event) => replaceContribution(rule.id, { amountCents: toCents(Number(event.target.value || 0)) })} /></label>
      <label>Haeufigkeit<select value={rule.frequency} onChange={(event) => replaceContribution(rule.id, { frequency: event.target.value as ContributionFrequency })}>{frequencySelect()}</select></label>
      <label>Ausfuehrung<select value={rule.execution} onChange={(event) => replaceContribution(rule.id, { execution: event.target.value as 'period-start' | 'period-end' })}><option value="period-start">Periodenanfang</option><option value="period-end">Periodenende</option></select></label>
      <label>Startdatum<input type="date" value={rule.startDate} onChange={(event) => replaceContribution(rule.id, { startDate: event.target.value })} /></label><label>Enddatum<input type="date" value={rule.endDate ?? ''} onChange={(event) => replaceContribution(rule.id, { endDate: event.target.value || undefined })} /></label>
      <label>Erhoehung p.a. in %<input type="number" step="0.01" value={rule.annualIncreasePercent ?? ''} onChange={(event) => replaceContribution(rule.id, { annualIncreasePercent: emptyToUndefined(event.target.value) })} /></label>
      <label>Erhoehung p.a. in EUR<input type="number" step="0.01" value={rule.annualIncreaseFixedCents === undefined ? '' : centsToEuro(rule.annualIncreaseFixedCents)} onChange={(event) => replaceContribution(rule.id, { annualIncreaseFixedCents: event.target.value === '' ? undefined : toCents(Number(event.target.value)) })} /></label>
      <label>Beschreibung<input value={rule.description ?? ''} onChange={(event) => replaceContribution(rule.id, { description: event.target.value || undefined })} /></label>
    </div><button type="button" className="danger-button" onClick={() => update({ contributionRules: draft.contributionRules.filter((item) => item.id !== rule.id) })}>Entfernen</button></div>)}</RuleSection>}

    {activeTab === 'Zuschuesse' && <RuleSection title="Zuschussregeln" onAdd={() => update({ subsidyRules: [...draft.subsidyRules, { id: createId(), type: 'employer', label: 'Neuer Zuschuss', amountCents: 0, frequency: 'monthly', startDate: draft.startDate, continueDuringPause: false }] })}>{draft.subsidyRules.map((rule) => <div className="rule-card" key={rule.id}><div className="editor-grid">
      <label>Bezeichnung<input value={rule.label} onChange={(event) => replaceSubsidy(rule.id, { label: event.target.value })} /></label><label>Art<select value={rule.type} onChange={(event) => replaceSubsidy(rule.id, { type: event.target.value as SubsidyRule['type'] })}><option value="employer">Arbeitgeber</option><option value="government">Staat</option><option value="bonus">Bonus</option><option value="other">Sonstiges</option></select></label>
      <label>Betrag in EUR<input type="number" min="0" step="0.01" value={centsToEuro(rule.amountCents)} onChange={(event) => replaceSubsidy(rule.id, { amountCents: toCents(Number(event.target.value || 0)) })} /></label><label>Haeufigkeit<select value={rule.frequency} onChange={(event) => replaceSubsidy(rule.id, { frequency: event.target.value as ContributionFrequency })}>{frequencySelect()}</select></label>
      <label>Startdatum<input type="date" value={rule.startDate} onChange={(event) => replaceSubsidy(rule.id, { startDate: event.target.value })} /></label><label>Enddatum<input type="date" value={rule.endDate ?? ''} onChange={(event) => replaceSubsidy(rule.id, { endDate: event.target.value || undefined })} /></label>
      <label>Erhoehung p.a. in %<input type="number" step="0.01" value={rule.annualIncreasePercent ?? ''} onChange={(event) => replaceSubsidy(rule.id, { annualIncreasePercent: emptyToUndefined(event.target.value) })} /></label><label className="toggle-field"><input type="checkbox" checked={rule.continueDuringPause} onChange={(event) => replaceSubsidy(rule.id, { continueDuringPause: event.target.checked })} /> Waerend Pause weiterzahlen</label>
    </div><button type="button" className="danger-button" onClick={() => update({ subsidyRules: draft.subsidyRules.filter((item) => item.id !== rule.id) })}>Entfernen</button></div>)}</RuleSection>}

    {activeTab === 'Rendite und Marktdaten' && <div className="editor-grid">
      <label>Renditemodus<select value={draft.returnMode} onChange={(event) => update({ returnMode: event.target.value as SavingsPlan['returnMode'] })}><option value="forecast">Prognose</option><option value="historical">Historisch</option></select></label>
      <label>Feste Rendite p.a. in %<input type="number" step="0.01" value={draft.forecastReturns.fixedAnnualPercent ?? ''} onChange={(event) => update({ forecastReturns: { ...draft.forecastReturns, fixedAnnualPercent: emptyToUndefined(event.target.value) } })} /></label><label>Minrendite p.a. in %<input type="number" step="0.01" value={draft.forecastReturns.minAnnualPercent ?? ''} onChange={(event) => update({ forecastReturns: { ...draft.forecastReturns, minAnnualPercent: emptyToUndefined(event.target.value) } })} /></label><label>Basisrendite p.a. in %<input type="number" step="0.01" value={draft.forecastReturns.baseAnnualPercent ?? ''} onChange={(event) => update({ forecastReturns: { ...draft.forecastReturns, baseAnnualPercent: emptyToUndefined(event.target.value) } })} /></label><label>Maxrendite p.a. in %<input type="number" step="0.01" value={draft.forecastReturns.maxAnnualPercent ?? ''} onChange={(event) => update({ forecastReturns: { ...draft.forecastReturns, maxAnnualPercent: emptyToUndefined(event.target.value) } })} /></label>
      <label>ISIN<input value={draft.historicalProduct?.isin ?? ''} onChange={(event) => update({ historicalProduct: { ...draft.historicalProduct, isin: event.target.value || undefined } })} /></label><label>WKN<input value={draft.historicalProduct?.wkn ?? ''} onChange={(event) => update({ historicalProduct: { ...draft.historicalProduct, wkn: event.target.value || undefined } })} /></label><label>Ticker<input value={draft.historicalProduct?.ticker ?? ''} onChange={(event) => update({ historicalProduct: { ...draft.historicalProduct, ticker: event.target.value || undefined } })} /></label><label>Boersenplatz<input value={draft.historicalProduct?.exchange ?? ''} onChange={(event) => update({ historicalProduct: { ...draft.historicalProduct, exchange: event.target.value || undefined } })} /></label><label>Datenquelle<input value={draft.historicalProduct?.dataSourceId ?? ''} onChange={(event) => update({ historicalProduct: { ...draft.historicalProduct, dataSourceId: event.target.value || undefined } })} /></label>
    </div>}

    {activeTab === 'Sparpausen' && <RuleSection title="Sparpausen" onAdd={() => update({ pauseRules: [...draft.pauseRules, { id: createId(), label: 'Neue Sparpause', startDate: draft.startDate, endDate: draft.startDate, pauseOwnContributions: true, pauseSubsidies: false, pauseFees: false, continueInterestAccrual: true }] })}>{draft.pauseRules.map((rule) => <div className="rule-card" key={rule.id}><div className="editor-grid"><label>Bezeichnung<input value={rule.label} onChange={(event) => replacePause(rule.id, { label: event.target.value })} /></label><label>Startdatum<input type="date" value={rule.startDate} onChange={(event) => replacePause(rule.id, { startDate: event.target.value })} /></label><label>Enddatum<input type="date" value={rule.endDate} onChange={(event) => replacePause(rule.id, { endDate: event.target.value })} /></label><label className="toggle-field"><input type="checkbox" checked={rule.pauseOwnContributions} onChange={(event) => replacePause(rule.id, { pauseOwnContributions: event.target.checked })} /> Einzahlungen pausieren</label><label className="toggle-field"><input type="checkbox" checked={rule.pauseSubsidies} onChange={(event) => replacePause(rule.id, { pauseSubsidies: event.target.checked })} /> Zuschuesse pausieren</label><label className="toggle-field"><input type="checkbox" checked={rule.pauseFees} onChange={(event) => replacePause(rule.id, { pauseFees: event.target.checked })} /> Gebuehren pausieren</label><label className="toggle-field"><input type="checkbox" checked={rule.continueInterestAccrual} onChange={(event) => replacePause(rule.id, { continueInterestAccrual: event.target.checked })} /> Verzinsung fortsetzen</label></div><button type="button" className="danger-button" onClick={() => update({ pauseRules: draft.pauseRules.filter((item) => item.id !== rule.id) })}>Entfernen</button></div>)}</RuleSection>}

    {activeTab === 'Gebuehren' && <RuleSection title="Gebuehrenregeln" onAdd={() => update({ feeRules: [...draft.feeRules, { id: createId(), name: 'Neue Gebuehr', type: 'fixed-monthly', amountCents: 0, startDate: draft.startDate, paymentFrequency: 'monthly', taxRelevant: false }] })}>{draft.feeRules.map((rule) => { const feeType = feeTypes.find((item) => item.value === rule.type); return <div className="rule-card" key={rule.id}><div className="editor-grid"><label>Name<input value={rule.name} onChange={(event) => replaceFee(rule.id, { name: event.target.value })} /></label><label>Typ<select value={rule.type} onChange={(event) => replaceFee(rule.id, { type: event.target.value as FeeType })}>{feeTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{feeType?.isPercent ? <label>Prozentsatz<input type="number" min="0" step="0.01" value={rule.percent ?? 0} onChange={(event) => replaceFee(rule.id, { percent: Number(event.target.value || 0) })} /></label> : <label>Betrag in EUR<input type="number" min="0" step="0.01" value={centsToEuro(rule.amountCents)} onChange={(event) => replaceFee(rule.id, { amountCents: toCents(Number(event.target.value || 0)) })} /></label>}<label>Startdatum<input type="date" value={rule.startDate} onChange={(event) => replaceFee(rule.id, { startDate: event.target.value })} /></label><label>Enddatum<input type="date" value={rule.endDate ?? ''} onChange={(event) => replaceFee(rule.id, { endDate: event.target.value || undefined })} /></label><label>Zahlungsrhythmus<select value={rule.paymentFrequency} onChange={(event) => replaceFee(rule.id, { paymentFrequency: event.target.value as ContributionFrequency })}>{frequencySelect()}</select></label><label className="toggle-field"><input type="checkbox" checked={rule.taxRelevant} onChange={(event) => replaceFee(rule.id, { taxRelevant: event.target.checked })} /> Steuerlich relevant</label></div><button type="button" className="danger-button" onClick={() => update({ feeRules: draft.feeRules.filter((item) => item.id !== rule.id) })}>Entfernen</button></div>; })}</RuleSection>}

    {activeTab === 'Steuern' && <div className="editor-grid"><p className="note editor-wide">Vereinfachte Steuersimulation, keine Steuerberatung.</p><label>Steuermodus<select value={draft.taxConfig.mode} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, mode: event.target.value as SavingsPlan['taxConfig']['mode'] } })}><option value="tax-free">Steuerfrei</option><option value="taxable">Steuerpflichtig</option><option value="disabled">Deaktiviert</option><option value="custom-rate">Eigener Satz</option></select></label><label>Steuersatz in %<input type="number" min="0" max="100" step="0.01" value={draft.taxConfig.personalTaxRatePercent ?? 0} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, personalTaxRatePercent: Number(event.target.value || 0) } })} /></label><label>Freibetrag in EUR<input type="number" min="0" step="0.01" value={centsToEuro(draft.taxConfig.annualAllowanceCents)} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, annualAllowanceCents: toCents(Number(event.target.value || 0)) } })} /></label><label>Teilfreistellung in %<input type="number" min="0" max="100" step="0.01" value={draft.taxConfig.partialExemptionPercent ?? 0} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, partialExemptionPercent: Number(event.target.value || 0) } })} /></label><label>Kirchensteuer in %<input type="number" min="0" max="100" step="0.01" value={draft.taxConfig.churchTaxPercent ?? 0} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, churchTaxPercent: Number(event.target.value || 0) } })} /></label><label className="toggle-field"><input type="checkbox" checked={draft.taxConfig.applyTaxAnnually} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, applyTaxAnnually: event.target.checked } })} /> Jaehrlich versteuern</label><label className="toggle-field"><input type="checkbox" checked={draft.taxConfig.visibleInChart} onChange={(event) => update({ taxConfig: { ...draft.taxConfig, visibleInChart: event.target.checked } })} /> Im Diagramm anzeigen</label></div>}

    {activeTab === 'Inflation' && <div className="editor-grid"><label className="toggle-field"><input type="checkbox" checked={draft.inflationConfig.enabled} onChange={(event) => update({ inflationConfig: { ...draft.inflationConfig, enabled: event.target.checked } })} /> Inflation beruecksichtigen</label><label>Feste Inflation p.a. in %<input type="number" min="0" step="0.01" value={draft.inflationConfig.fixedAnnualRatePercent ?? 0} onChange={(event) => update({ inflationConfig: { ...draft.inflationConfig, fixedAnnualRatePercent: Number(event.target.value || 0) } })} /></label><label>Min. Inflation p.a. in %<input type="number" min="0" step="0.01" value={draft.inflationConfig.minAnnualRatePercent ?? 0} onChange={(event) => update({ inflationConfig: { ...draft.inflationConfig, minAnnualRatePercent: Number(event.target.value || 0) } })} /></label><label>Basis-Inflation p.a. in %<input type="number" min="0" step="0.01" value={draft.inflationConfig.baseAnnualRatePercent ?? 0} onChange={(event) => update({ inflationConfig: { ...draft.inflationConfig, baseAnnualRatePercent: Number(event.target.value || 0) } })} /></label><label>Max. Inflation p.a. in %<input type="number" min="0" step="0.01" value={draft.inflationConfig.maxAnnualRatePercent ?? 0} onChange={(event) => update({ inflationConfig: { ...draft.inflationConfig, maxAnnualRatePercent: Number(event.target.value || 0) } })} /></label></div>}

    {activeTab === 'Auszahlungen' && <RuleSection title="Auszahlungsregeln" onAdd={() => update({ withdrawalRules: [...draft.withdrawalRules, { id: createId(), type: 'monthly', amountCents: 0, startDate: draft.startDate }] })}>{draft.withdrawalRules.map((rule) => <div className="rule-card" key={rule.id}><div className="editor-grid"><label>Entnahmeart<select value={rule.type} onChange={(event) => replaceWithdrawal(rule.id, { type: event.target.value as WithdrawalRule['type'] })}><option value="one-time">Einmalig</option><option value="monthly">Monatlich</option><option value="annual">Jaehrlich</option><option value="percentage">Prozentual</option></select></label>{rule.type === 'percentage' ? <label>Prozentsatz<input type="number" min="0" max="100" step="0.01" value={rule.percentage ?? 0} onChange={(event) => replaceWithdrawal(rule.id, { percentage: Number(event.target.value || 0) })} /></label> : <label>Betrag in EUR<input type="number" min="0" step="0.01" value={centsToEuro(rule.amountCents)} onChange={(event) => replaceWithdrawal(rule.id, { amountCents: toCents(Number(event.target.value || 0)) })} /></label>}<label>Startdatum<input type="date" value={rule.startDate} onChange={(event) => replaceWithdrawal(rule.id, { startDate: event.target.value })} /></label><label>Enddatum<input type="date" value={rule.endDate ?? ''} onChange={(event) => replaceWithdrawal(rule.id, { endDate: event.target.value || undefined })} /></label></div><button type="button" className="danger-button" onClick={() => update({ withdrawalRules: draft.withdrawalRules.filter((item) => item.id !== rule.id) })}>Entfernen</button></div>)}</RuleSection>}

    {activeTab === 'Vorschau' && <div className="preview-list"><p>Einzahlungsregeln: {draft.contributionRules.length}</p><p>Zuschussregeln: {draft.subsidyRules.length}</p><p>Sparpausen: {draft.pauseRules.length}</p><p>Gebuehrenregeln: {draft.feeRules.length}</p><p>Auszahlungsregeln: {draft.withdrawalRules.length}</p><p className="note">Aenderungen werden nach dem Speichern sofort neu berechnet.</p></div>}
    {error && <p role="alert" className="error">{error}</p>}
    <footer className="editor-footer"><button type="button" disabled={isSaving} onClick={() => void save()}>{isSaving ? 'Speichert ...' : 'Speichern'}</button></footer>
  </section>;
};
